var _function_extras_8hpp =
[
    [ "wpi::util::detail::UniqueFunctionBase&lt; ReturnT, ParamTs &gt;", "classwpi_1_1util_1_1detail_1_1_unique_function_base.html", "classwpi_1_1util_1_1detail_1_1_unique_function_base" ],
    [ "wpi::util::detail::UniqueFunctionBase&lt; ReturnT, ParamTs &gt;::AdjustedParamTBase&lt; T &gt;", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_adjusted_param_t_base.html", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_adjusted_param_t_base" ],
    [ "wpi::util::detail::UniqueFunctionBase&lt; ReturnT, ParamTs &gt;::AdjustedParamTBase&lt; T &amp; &gt;", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_adjusted_param_t_base_3_01_t_01_6_01_4.html", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_adjusted_param_t_base_3_01_t_01_6_01_4" ],
    [ "wpi::util::detail::UniqueFunctionBase&lt; ReturnT, ParamTs &gt;::AdjustedParamTBase&lt; T &amp;&amp; &gt;", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_adjusted_param_t_base_3_01_t_01_6_6_01_4.html", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_adjusted_param_t_base_3_01_t_01_6_6_01_4" ],
    [ "wpi::util::detail::UniqueFunctionBase&lt; ReturnT, ParamTs &gt;::TrivialCallback", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_trivial_callback.html", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_trivial_callback" ],
    [ "wpi::util::detail::UniqueFunctionBase&lt; ReturnT, ParamTs &gt;::NonTrivialCallbacks", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_non_trivial_callbacks.html", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_non_trivial_callbacks" ],
    [ "wpi::util::detail::UniqueFunctionBase&lt; ReturnT, ParamTs &gt;::StorageUnionT", "unionwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_storage_union_t.html", "unionwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_storage_union_t" ],
    [ "wpi::util::detail::UniqueFunctionBase&lt; ReturnT, ParamTs &gt;::StorageUnionT::OutOfLineStorageT", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_storage_union_t_1_1_out_of_line_storage_t.html", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_storage_union_t_1_1_out_of_line_storage_t" ],
    [ "wpi::util::detail::UniqueFunctionBase&lt; ReturnT, ParamTs &gt;::CallbacksHolder&lt; CallableT, CalledAs &gt;", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_callbacks_holder.html", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_callbacks_holder" ],
    [ "wpi::util::detail::UniqueFunctionBase&lt; ReturnT, ParamTs &gt;::CalledAs&lt; T &gt;", "structwpi_1_1util_1_1detail_1_1_unique_function_base_1_1_called_as.html", null ],
    [ "wpi::util::unique_function&lt; R(P...)&gt;", "classwpi_1_1util_1_1unique__function_3_01_r_07_p_8_8_8_08_4.html", "classwpi_1_1util_1_1unique__function_3_01_r_07_p_8_8_8_08_4" ],
    [ "wpi::util::unique_function&lt; R(P...) const &gt;", "classwpi_1_1util_1_1unique__function_3_01_r_07_p_8_8_8_08_01const_01_4.html", "classwpi_1_1util_1_1unique__function_3_01_r_07_p_8_8_8_08_01const_01_4" ],
    [ "wpi::util::detail::EnableIfCallable", "namespacewpi_1_1util_1_1detail.html#a236459257e0ef0ad823fd494507ec4c5", null ],
    [ "wpi::util::detail::EnableUnlessSameType", "namespacewpi_1_1util_1_1detail.html#aad758efc285f6bc6c6a44f410d64d333", null ]
];