var searchData=
[
  ['ramsetecommand_0',['RamseteCommand',['../classfrc2_1_1_ramsete_command.html',1,'frc2']]],
  ['ramsetecontroller_1',['RamseteController',['../classfrc_1_1_ramsete_controller.html',1,'frc']]],
  ['range_5fformat_5fkind_2',['range_format_kind',['../structrange__format__kind.html',1,'']]],
  ['range_5fformat_5fkind_5f_3',['range_format_kind_',['../structdetail_1_1range__format__kind__.html',1,'detail']]],
  ['range_5fformatter_4',['range_formatter',['../structrange__formatter.html',1,'']]],
  ['range_5fformatter_3c_20detail_3a_3auncvref_5ftype_3c_20range_5ftype_20_3e_2c_20char_20_3e_5',['range_formatter&lt; detail::uncvref_type&lt; range_type &gt;, Char &gt;',['../structrange__formatter.html',1,'']]],
  ['range_5fformatter_3c_20t_2c_20char_2c_20enable_5fif_5ft_3c_20conjunction_3c_20std_3a_3ais_5fsame_3c_20t_2c_20remove_5fcvref_5ft_3c_20t_20_3e_20_3e_2c_20is_5fformattable_3c_20t_2c_20char_20_3e_20_3e_3a_3avalue_20_3e_20_3e_6',['range_formatter&lt; T, Char, enable_if_t&lt; conjunction&lt; std::is_same&lt; T, remove_cvref_t&lt; T &gt; &gt;, is_formattable&lt; T, Char &gt; &gt;::value &gt; &gt;',['../structrange__formatter_3_01_t_00_01_char_00_01enable__if__t_3_01conjunction_3_01std_1_1is__same_edf46378efa9da3f820c5aa7a483895e.html',1,'']]],
  ['raw_5ffd_5fistream_7',['raw_fd_istream',['../classwpi_1_1raw__fd__istream.html',1,'wpi']]],
  ['raw_5fistream_8',['raw_istream',['../classwpi_1_1raw__istream.html',1,'wpi']]],
  ['raw_5fmem_5fistream_9',['raw_mem_istream',['../classwpi_1_1raw__mem__istream.html',1,'wpi']]],
  ['raw_5fos_5fostream_10',['raw_os_ostream',['../classwpi_1_1raw__os__ostream.html',1,'wpi']]],
  ['raw_5fsocket_5fistream_11',['raw_socket_istream',['../classwpi_1_1raw__socket__istream.html',1,'wpi']]],
  ['raw_5fsocket_5fostream_12',['raw_socket_ostream',['../classwpi_1_1raw__socket__ostream.html',1,'wpi']]],
  ['raw_5fuv_5fostream_13',['raw_uv_ostream',['../classwpi_1_1raw__uv__ostream.html',1,'wpi']]],
  ['rawentry_14',['RawEntry',['../classnt_1_1_raw_entry.html',1,'nt']]],
  ['rawevent_15',['RawEvent',['../structcs_1_1_raw_event.html',1,'cs']]],
  ['rawframe_16',['RawFrame',['../structwpi_1_1_raw_frame.html',1,'wpi']]],
  ['rawlogentry_17',['RawLogEntry',['../classwpi_1_1log_1_1_raw_log_entry.html',1,'wpi::log']]],
  ['rawpublisher_18',['RawPublisher',['../classnt_1_1_raw_publisher.html',1,'nt']]],
  ['rawsink_19',['RawSink',['../classcs_1_1_raw_sink.html',1,'cs']]],
  ['rawsource_20',['RawSource',['../classcs_1_1_raw_source.html',1,'cs']]],
  ['rawsubscriber_21',['RawSubscriber',['../classnt_1_1_raw_subscriber.html',1,'nt']]],
  ['rawtopic_22',['RawTopic',['../classnt_1_1_raw_topic.html',1,'nt']]],
  ['recordingcontroller_23',['RecordingController',['../classfrc_1_1detail_1_1_recording_controller.html',1,'frc::detail']]],
  ['rectangle2d_24',['Rectangle2d',['../classfrc_1_1_rectangle2d.html',1,'frc']]],
  ['rectangularregionconstraint_25',['RectangularRegionConstraint',['../classfrc_1_1_rectangular_region_constraint.html',1,'frc']]],
  ['recursive_5fspinlock1_26',['recursive_spinlock1',['../classwpi_1_1recursive__spinlock1.html',1,'wpi']]],
  ['recursive_5fspinlock2_27',['recursive_spinlock2',['../classwpi_1_1recursive__spinlock2.html',1,'wpi']]],
  ['ref_28',['ref',['../structwpi_1_1support_1_1detail_1_1packed__endian__specific__integral_1_1ref.html',1,'wpi::support::detail::packed_endian_specific_integral']]],
  ['referenceproxy_29',['ReferenceProxy',['../classwpi_1_1iterator__facade__base_1_1_reference_proxy.html',1,'wpi::iterator_facade_base']]],
  ['relay_30',['Relay',['../classfrc_1_1_relay.html',1,'frc']]],
  ['relaydoao_31',['RelayDOAO',['../struct_h_a_l___h_m_b_data_1_1_relay_d_o_a_o.html',1,'HAL_HMBData']]],
  ['relaysim_32',['RelaySim',['../classfrc_1_1sim_1_1_relay_sim.html',1,'frc::sim']]],
  ['remove_5fcvref_33',['remove_cvref',['../structwpi_1_1remove__cvref.html',1,'wpi']]],
  ['repeatcommand_34',['RepeatCommand',['../classfrc2_1_1_repeat_command.html',1,'frc2']]],
  ['request_35',['Request',['../classwpi_1_1uv_1_1_request.html',1,'wpi::uv']]],
  ['requestimpl_36',['RequestImpl',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20connectreq_2c_20uv_5fconnect_5ft_20_3e_37',['RequestImpl&lt; ConnectReq, uv_connect_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20getaddrinforeq_2c_20uv_5fgetaddrinfo_5ft_20_3e_38',['RequestImpl&lt; GetAddrInfoReq, uv_getaddrinfo_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20getnameinforeq_2c_20uv_5fgetnameinfo_5ft_20_3e_39',['RequestImpl&lt; GetNameInfoReq, uv_getnameinfo_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20shutdownreq_2c_20uv_5fshutdown_5ft_20_3e_40',['RequestImpl&lt; ShutdownReq, uv_shutdown_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20udpsendreq_2c_20uv_5fudp_5fsend_5ft_20_3e_41',['RequestImpl&lt; UdpSendReq, uv_udp_send_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20workreq_2c_20uv_5fwork_5ft_20_3e_42',['RequestImpl&lt; WorkReq, uv_work_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requestimpl_3c_20writereq_2c_20uv_5fwrite_5ft_20_3e_43',['RequestImpl&lt; WriteReq, uv_write_t &gt;',['../classwpi_1_1uv_1_1_request_impl.html',1,'wpi::uv']]],
  ['requirements_44',['Requirements',['../classfrc2_1_1_requirements.html',1,'frc2']]],
  ['resource_45',['Resource',['../classfrc_1_1_resource.html',1,'frc']]],
  ['results_46',['Results',['../classfrc_1_1_april_tag_detector_1_1_results.html',1,'frc::AprilTagDetector']]],
  ['revphsim_47',['REVPHSim',['../classfrc_1_1sim_1_1_r_e_v_p_h_sim.html',1,'frc::sim']]],
  ['rgb_48',['rgb',['../structrgb.html',1,'']]],
  ['roboriosim_49',['RoboRioSim',['../classfrc_1_1sim_1_1_robo_rio_sim.html',1,'frc::sim']]],
  ['robotbase_50',['RobotBase',['../classfrc_1_1_robot_base.html',1,'frc']]],
  ['robotcontroller_51',['RobotController',['../classfrc_1_1_robot_controller.html',1,'frc']]],
  ['robotdrivebase_52',['RobotDriveBase',['../classfrc_1_1_robot_drive_base.html',1,'frc']]],
  ['robotmodetriggers_53',['RobotModeTriggers',['../classfrc2_1_1_robot_mode_triggers.html',1,'frc2']]],
  ['robotstate_54',['RobotState',['../classfrc_1_1_robot_state.html',1,'frc']]],
  ['romigyro_55',['RomiGyro',['../classfrc_1_1_romi_gyro.html',1,'frc']]],
  ['romimotor_56',['RomiMotor',['../classfrc_1_1_romi_motor.html',1,'frc']]],
  ['rotated_5fspan_57',['rotated_span',['../classwpi_1_1rotated__span.html',1,'wpi']]],
  ['rotation2d_58',['Rotation2d',['../classfrc_1_1_rotation2d.html',1,'frc']]],
  ['rotation3d_59',['Rotation3d',['../classfrc_1_1_rotation3d.html',1,'frc']]],
  ['runcommand_60',['RunCommand',['../classfrc2_1_1_run_command.html',1,'frc2']]],
  ['runtime_5fformat_5fstring_61',['runtime_format_string',['../structruntime__format__string.html',1,'']]],
  ['runtimeerror_62',['RuntimeError',['../classfrc_1_1_runtime_error.html',1,'frc']]]
];
